# DeepLearning with Pytorch
DataCamp Course

In [1]:
# pip install torch
import numpy as np
import torch

## Creating tensors in PyTorch
Random tensors are very important in neural networks. Parameters of the neural networks typically are initialized with random weights (random tensors).



In [2]:
list1=[2,3,5]
list2=[1,2,9]
torch.tensor([list1,list2])

tensor([[2, 3, 5],
        [1, 2, 9]])

In [3]:
np.array([list1,list2])

array([[2, 3, 5],
       [1, 2, 9]])

In [4]:
#multiplcation with pytorch
mat1=torch.rand(4,4)
mat2=torch.rand(4,4)
multmat=torch.matmul(mat1,mat2)
multmat

tensor([[0.2116, 0.8931, 1.1053, 1.2417],
        [0.7121, 1.8380, 1.7494, 1.6751],
        [0.5606, 1.6617, 1.6932, 1.7045],
        [0.6332, 1.7012, 1.6254, 1.6284]])

In [5]:
#element multiplication
mat1 * mat2

tensor([[0.0369, 0.1220, 0.1328, 0.7770],
        [0.0877, 0.3180, 0.5295, 0.0727],
        [0.3881, 0.4471, 0.4921, 0.4328],
        [0.0460, 0.1642, 0.5739, 0.2692]])

In [6]:
#multiplication with Numpy
mat1=np.random.rand(4,4)
mat2=np.random.rand(4,4)
multmat=np.dot(mat1,mat2)
multmat

array([[1.35642541, 1.01426486, 1.10246561, 0.78203579],
       [0.55005192, 0.69566628, 0.65782618, 0.41660342],
       [1.12589128, 1.12815996, 1.07644265, 0.99476697],
       [1.16448307, 0.60912685, 0.9926406 , 0.43241657]])

In [7]:
#element multiplication
np.multiply(mat1,mat2)

array([[0.58918873, 0.06954663, 0.21220215, 0.06804284],
       [0.07824101, 0.11137922, 0.60596362, 0.10961892],
       [0.02948115, 0.39719895, 0.38805566, 0.11387326],
       [0.39490481, 0.12170485, 0.05764186, 0.09092363]])

In [8]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [9]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [10]:
torch.eye(2,2)

tensor([[1., 0.],
        [0., 1.]])

In [11]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [12]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [13]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [14]:
torch.from_numpy(np.identity(2))

tensor([[1., 0.],
        [0., 1.]], dtype=torch.float64)

In [15]:
torch.eye(2,2).numpy()

array([[1., 0.],
       [0., 1.]], dtype=float32)

In [16]:
# Create random tensor of size 3 by 3
your_first_tensor = torch.rand(3, 3)

# Calculate the shape of the tensor
tensor_size = your_first_tensor.shape

# Print the values of the tensor and its shape
print(your_first_tensor)
print(tensor_size)

tensor([[0.8301, 0.8794, 0.0787],
        [0.1774, 0.1400, 0.9124],
        [0.6530, 0.0886, 0.7491]])
torch.Size([3, 3])


In [17]:
#same things in Numpy
# Create random tensor of size 3 by 3
your_first_tensor = np.random.rand(3, 3)

# Calculate the shape of the tensor
tensor_size = your_first_tensor.shape

# Print the values of the tensor and its shape
print(your_first_tensor)
print(tensor_size)

[[0.87257697 0.52333956 0.04170395]
 [0.60312084 0.81883652 0.75864398]
 [0.87435081 0.93170424 0.03689864]]
(3, 3)


In [18]:
# Create a matrix of ones with shape 3 by 3
tensor_of_ones = torch.ones(3, 3)

# Create an identity matrix with shape 3 by 3
identity_tensor = torch.eye(3)

# Do a matrix multiplication of tensor_of_ones with identity_tensor
matrices_multiplied = torch.matmul(tensor_of_ones, identity_tensor)
print(matrices_multiplied)

# Do an element-wise multiplication of tensor_of_ones with identity_tensor
element_multiplication = tensor_of_ones*identity_tensor
print(element_multiplication)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


## Forward pass
Let's have something resembling more a neural network. The computational graph has been given below. You are going to initialize 3 large random tensors, and then do the operations as given in the computational graph. The final operation is the mean of the tensor, given by torch.mean(your_tensor).

In [19]:
# Initialize tensors x, y and z
x = torch.rand(1000, 1000)
y = torch.rand(1000, 1000)
z = torch.rand(1000, 1000)

# Multiply x with y
q = torch.matmul(x,y)

# Multiply elementwise z with q
f = torch.matmul(z,q)

mean_f = torch.mean(f)
print(mean_f)

tensor(125066.8906)


## Backpropagation using PyTorch
Here, you are going to use automatic differentiation of PyTorch in order to compute the derivatives of x, y and z from the previous exercise.

In [20]:
# Initialize x, y and z to values 4, -3 and 5
x = torch.tensor([4.], requires_grad=True)
y = torch.tensor([-3.], requires_grad=True)
z = torch.tensor([5.],requires_grad=True)

# Set q to sum of x and y, set f to product of q with z
q = x+y
f = z*q

# Compute the derivatives
f.backward()

# Print the gradients
print("Gradient of x is: " + str(x.grad))
print("Gradient of y is: " + str(y.grad))
print("Gradient of z is: " + str(z.grad))

Gradient of x is: tensor([5.])
Gradient of y is: tensor([5.])
Gradient of z is: tensor([1.])


In [21]:
x = torch.tensor(torch.rand(5,5).requires_grad_(True), requires_grad=True)
y = torch.tensor(torch.rand(5,5).requires_grad_(True), requires_grad=True)
z = torch.tensor(torch.rand(5,5).requires_grad_(True),requires_grad=True)

# Multiply tensors x and y
q = torch.matmul(x,y)

# Elementwise multiply tensors z with q
f = z*q

mean_f = torch.mean(f)

# Calculate the gradients
mean_f.backward(
)
print("Gradient of x is: " + str(x.grad))
print("Gradient of y is: " + str(y.grad))
print("Gradient of z is: " + str(z.grad))

Gradient of x is: tensor([[0.0388, 0.0440, 0.0600, 0.0617, 0.0295],
        [0.0442, 0.0344, 0.0619, 0.0581, 0.0503],
        [0.0196, 0.0207, 0.0326, 0.0462, 0.0269],
        [0.0387, 0.0309, 0.0424, 0.0521, 0.0365],
        [0.0201, 0.0224, 0.0437, 0.0581, 0.0374]])
Gradient of y is: tensor([[0.0604, 0.0512, 0.0465, 0.0368, 0.0560],
        [0.0522, 0.0516, 0.0422, 0.0489, 0.0645],
        [0.0718, 0.0664, 0.0531, 0.0504, 0.0719],
        [0.0385, 0.0365, 0.0311, 0.0253, 0.0380],
        [0.0206, 0.0327, 0.0215, 0.0205, 0.0313]])
Gradient of z is: tensor([[0.0213, 0.0432, 0.0611, 0.0159, 0.0261],
        [0.0425, 0.0786, 0.1005, 0.0430, 0.0542],
        [0.0435, 0.0418, 0.0730, 0.0370, 0.0364],
        [0.0233, 0.0646, 0.0797, 0.0226, 0.0400],
        [0.0229, 0.0630, 0.0884, 0.0131, 0.0435]])


/var/folders/vv/qbkrt9vj4_j3xx714txsmc900000gn/T/ipykernel_87158/1950033724.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(torch.rand(5,5).requires_grad_(True), requires_grad=True)
/var/folders/vv/qbkrt9vj4_j3xx714txsmc900000gn/T/ipykernel_87158/1950033724.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y = torch.tensor(torch.rand(5,5).requires_grad_(True), requires_grad=True)
/var/folders/vv/qbkrt9vj4_j3xx714txsmc900000gn/T/ipykernel_87158/1950033724.py:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  z = torch.

In [22]:
x = torch.rand(5,5).clone().detach().requires_grad_(True)
y = torch.rand(5,5).clone().detach().requires_grad_(True)
z = torch.rand(5,5).clone().detach().requires_grad_(True)

# Multiply tensors x and y
q = torch.matmul(x,y)

# Elementwise multiply tensors z with q
f = z*q

mean_f = torch.mean(f)

# Calculate the gradients
mean_f.backward(
)
print("Gradient of x is: " + str(x.grad))
print("Gradient of y is: " + str(y.grad))
print("Gradient of z is: " + str(z.grad))

Gradient of x is: tensor([[0.0494, 0.0418, 0.0150, 0.0242, 0.0162],
        [0.0865, 0.0803, 0.0424, 0.0498, 0.0357],
        [0.0456, 0.0341, 0.0288, 0.0348, 0.0290],
        [0.1085, 0.1065, 0.0489, 0.0622, 0.0391],
        [0.0541, 0.0514, 0.0329, 0.0403, 0.0276]])
Gradient of y is: tensor([[0.0135, 0.0138, 0.0263, 0.0129, 0.0181],
        [0.0255, 0.0299, 0.0336, 0.0349, 0.0406],
        [0.0323, 0.0367, 0.0589, 0.0442, 0.0504],
        [0.0513, 0.0421, 0.0738, 0.0452, 0.0621],
        [0.0364, 0.0252, 0.0535, 0.0321, 0.0412]])
Gradient of z is: tensor([[0.0512, 0.0348, 0.0283, 0.0448, 0.0364],
        [0.0522, 0.0347, 0.0255, 0.0330, 0.0291],
        [0.0806, 0.0467, 0.0436, 0.0773, 0.0437],
        [0.0371, 0.0209, 0.0254, 0.0480, 0.0222],
        [0.0327, 0.0222, 0.0199, 0.0359, 0.0226]])


## Introduction to Neural Networks

In [23]:
import torch.nn as nn
class Net(nn.Module):
    def __init__(self):
        super(Net,self).__init__()
        self.fc1=nn.Linear(10,20)
        self.fc2=nn.Linear(20,20)
        self.output=nn.Linear(20,4)
    
    def forward(self,x):
        x=self.fc1(x)
        x=self.fc2(x)
        x=self.output(x)
        return x

## Your first neural network

In [24]:
input_layer=torch.tensor([0.6274, 0.1628, 0.0105, 0.6633, 0.8410, 0.9622, 0.5430, 0.1063, 0.9469,
        0.6349, 0.4724, 0.8962, 0.4189, 0.1548, 0.1493, 0.8707, 0.5688, 0.5573,
        0.0200, 0.0686, 0.4835, 0.6485, 0.6707, 0.4840, 0.3334, 0.4511, 0.9080,
        0.7644, 0.1195, 0.2261, 0.7179, 0.0761, 0.3053, 0.4166, 0.5864, 0.7685,
        0.1430, 0.5032, 0.7597, 0.0178, 0.6681, 0.7929, 0.2807, 0.4565, 0.8951,
        0.9561, 0.7653, 0.6765, 0.9817, 0.6979, 0.7538, 0.9748, 0.7861, 0.9306,
        0.9722, 0.9187, 0.8236, 0.9616, 0.7018, 0.0258, 0.0731, 0.9699, 0.7713,
        0.4656, 0.9950, 0.3696, 0.1254, 0.8638, 0.8701, 0.2393, 0.3418, 0.9012,
        0.9166, 0.5226, 0.6390, 0.0909, 0.3148, 0.8039, 0.0611, 0.9445, 0.6347,
        0.4432, 0.2790, 0.2889, 0.9711, 0.1181, 0.4634, 0.7296, 0.7302, 0.0958,
        0.3579, 0.9335, 0.0541, 0.5110, 0.9313, 0.9353, 0.8248, 0.7672, 0.8618,
        0.2105, 0.2097, 0.3595, 0.9828, 0.8052, 0.5623, 0.4507, 0.8317, 0.6206,
        0.8855, 0.4178, 0.6278, 0.9567, 0.6079, 0.1040, 0.4751, 0.2636, 0.3625,
        0.5574, 0.0900, 0.9821, 0.8419, 0.2119, 0.6282, 0.6375, 0.8404, 0.5817,
        0.0633, 0.1094, 0.8001, 0.1383, 0.6686, 0.9489, 0.1063, 0.2051, 0.2793,
        0.3043, 0.5426, 0.2457, 0.4038, 0.2180, 0.1121, 0.6242, 0.4385, 0.4078,
        0.6300, 0.1212, 0.8940, 0.7061, 0.7006, 0.5300, 0.8381, 0.0929, 0.2237,
        0.6057, 0.6795, 0.3592, 0.1843, 0.8313, 0.9316, 0.4711, 0.7772, 0.3189,
        0.9250, 0.5971, 0.6421, 0.4656, 0.0310, 0.9607, 0.7106, 0.6802, 0.3676,
        0.6078, 0.4095, 0.5095, 0.3669, 0.7016, 0.5492, 0.0474, 0.7545, 0.2482,
        0.3864, 0.9002, 0.3000, 0.5919, 0.1773, 0.4446, 0.1377, 0.2447, 0.9677,
        0.1152, 0.4857, 0.8567, 0.3289, 0.3638, 0.8760, 0.3630, 0.2672, 0.0645,
        0.1536, 0.6036, 0.8734, 0.3902, 0.3835, 0.9550, 0.8062, 0.0047, 0.8578,
        0.8310, 0.8201, 0.2708, 0.0899, 0.9097, 0.2591, 0.5464, 0.6138, 0.5002,
        0.1195, 0.1239, 0.6613, 0.6476, 0.0504, 0.0474, 0.0945, 0.0943, 0.1234,
        0.3878, 0.1829, 0.9172, 0.1222, 0.1997, 0.5461, 0.8090, 0.5002, 0.0903,
        0.7348, 0.7095, 0.8977, 0.5200, 0.6694, 0.3033, 0.5274, 0.3223, 0.9344,
        0.3289, 0.6532, 0.1864, 0.9603, 0.7124, 0.8679, 0.1951, 0.2558, 0.6891,
        0.4872, 0.3452, 0.8574, 0.6138, 0.7648, 0.0508, 0.1915, 0.6385, 0.2517,
        0.0343, 0.9342, 0.0085, 0.1787, 0.9223, 0.5225, 0.4298, 0.8072, 0.1690,
        0.4359, 0.4455, 0.3837, 0.5182, 0.6745, 0.6476, 0.7497, 0.0625, 0.8902,
        0.5101, 0.5854, 0.9254, 0.3715, 0.6616, 0.9244, 0.0883, 0.9359, 0.5922,
        0.6528, 0.5998, 0.7910, 0.6105, 0.4047, 0.1938, 0.6226, 0.3755, 0.4061,
        0.6352, 0.2772, 0.8613, 0.7408, 0.4106, 0.7942, 0.7016, 0.8505, 0.6679,
        0.2560, 0.0759, 0.6633, 0.1086, 0.7507, 0.6377, 0.2026, 0.0223, 0.3009,
        0.0222, 0.2138, 0.3709, 0.9074, 0.2739, 0.7103, 0.8604, 0.8750, 0.0486,
        0.0187, 0.9253, 0.2470, 0.6574, 0.0066, 0.6755, 0.4065, 0.9068, 0.4744,
        0.5363, 0.9796, 0.3140, 0.4309, 0.8053, 0.8039, 0.9486, 0.9036, 0.0814,
        0.9019, 0.8640, 0.7559, 0.4222, 0.7802, 0.6346, 0.5255, 0.8017, 0.3384,
        0.8510, 0.5992, 0.1188, 0.8940, 0.6073, 0.7123, 0.5553, 0.7105, 0.3690,
        0.5963, 0.4908, 0.8723, 0.3982, 0.6212, 0.2471, 0.2201, 0.4784, 0.3757,
        0.9922, 0.4075, 0.2777, 0.7578, 0.5890, 0.9802, 0.9046, 0.0186, 0.0603,
        0.5316, 0.2291, 0.6817, 0.9995, 0.2710, 0.5372, 0.4278, 0.7349, 0.8481,
        0.0103, 0.7186, 0.3003, 0.0757, 0.5862, 0.8175, 0.4136, 0.9896, 0.1383,
        0.6178, 0.4393, 0.7352, 0.6179, 0.4947, 0.9938, 0.6796, 0.5053, 0.5859,
        0.6953, 0.8672, 0.6209, 0.6199, 0.0715, 0.0893, 0.5287, 0.3730, 0.4308,
        0.1440, 0.7531, 0.1393, 0.8627, 0.3118, 0.5765, 0.3637, 0.2072, 0.4622,
        0.7490, 0.1405, 0.5106, 0.5696, 0.9282, 0.3015, 0.8621, 0.0843, 0.3542,
        0.1899, 0.9767, 0.6239, 0.0879, 0.2002, 0.8724, 0.8527, 0.1820, 0.0726,
        0.6260, 0.9226, 0.6986, 0.8851, 0.8241, 0.6838, 0.4734, 0.1823, 0.3448,
        0.0255, 0.5838, 0.8862, 0.7693, 0.7174, 0.6429, 0.3211, 0.7278, 0.1152,
        0.3688, 0.5322, 0.5166, 0.9932, 0.2026, 0.5758, 0.5100, 0.9294, 0.5002,
        0.0537, 0.4932, 0.1603, 0.7118, 0.5838, 0.3247, 0.1559, 0.4276, 0.1471,
        0.2524, 0.9983, 0.7813, 0.3247, 0.0062, 0.7494, 0.4300, 0.9840, 0.2706,
        0.9861, 0.6522, 0.7436, 0.0484, 0.2843, 0.8315, 0.7243, 0.7801, 0.7989,
        0.5740, 0.0850, 0.3551, 0.5676, 0.2451, 0.4846, 0.6104, 0.6161, 0.3950,
        0.9011, 0.3380, 0.1383, 0.6385, 0.6433, 0.5765, 0.9603, 0.7705, 0.5176,
        0.9671, 0.1871, 0.2954, 0.1469, 0.8491, 0.0615, 0.3821, 0.5330, 0.3071,
        0.6586, 0.4149, 0.6667, 0.9799, 0.9546, 0.5719, 0.3691, 0.2231, 0.1005,
        0.2126, 0.6493, 0.1569, 0.4168, 0.8382, 0.4683, 0.8322, 0.5402, 0.0938,
        0.9071, 0.6710, 0.5627, 0.5906, 0.2475, 0.9399, 0.8678, 0.1236, 0.5178,
        0.5330, 0.5088, 0.9882, 0.5531, 0.8191, 0.7997, 0.3246, 0.8954, 0.5366,
        0.8842, 0.5524, 0.7503, 0.5147, 0.1962, 0.0220, 0.5823, 0.8548, 0.6321,
        0.6713, 0.5514, 0.9558, 0.7700, 0.3856, 0.9451, 0.0719, 0.0754, 0.2018,
        0.9217, 0.5858, 0.0058, 0.9407, 0.6209, 0.7813, 0.1995, 0.9898, 0.5754,
        0.6189, 0.8530, 0.5089, 0.9096, 0.0272, 0.4524, 0.1988, 0.8466, 0.4177,
        0.0744, 0.8159, 0.7202, 0.2515, 0.0220, 0.3497, 0.2945, 0.6423, 0.8847,
        0.9293, 0.0081, 0.6630, 0.5683, 0.3010, 0.6980, 0.2960, 0.2468, 0.4636,
        0.2846, 0.1816, 0.9419, 0.4749, 0.6570, 0.4684, 0.1486, 0.1224, 0.4565,
        0.7340, 0.1187, 0.6500, 0.2170, 0.4485, 0.0187, 0.2235, 0.0650, 0.2540,
        0.1107, 0.2199, 0.4994, 0.9825, 0.5844, 0.0525, 0.6698, 0.2779, 0.7663,
        0.8748, 0.5847, 0.7340, 0.7407, 0.4555, 0.6858, 0.1607, 0.0186, 0.4795,
        0.9957, 0.5038, 0.9187, 0.4030, 0.9589, 0.5572, 0.4669, 0.9462, 0.0258,
        0.6539, 0.6233, 0.9980, 0.0795, 0.0937, 0.6293, 0.6028, 0.2794, 0.9713,
        0.3018, 0.7522, 0.6013, 0.9002, 0.5612, 0.6520, 0.5411, 0.0794, 0.0143,
        0.4010, 0.0303, 0.4704, 0.8371, 0.4937, 0.4177, 0.0069, 0.0328, 0.6072,
        0.2529, 0.5998, 0.2012, 0.2015, 0.5254, 0.2900, 0.9913, 0.9110, 0.5651,
        0.9724, 0.5496, 0.0188, 0.1534, 0.4927, 0.4294, 0.8905, 0.3925, 0.4396,
        0.9054, 0.1075, 0.9537, 0.3423, 0.2844, 0.0609, 0.8197, 0.0816, 0.5794,
        0.9540, 0.2981, 0.0290, 0.6464, 0.2021, 0.0120, 0.9153, 0.2589, 0.1380,
        0.3324, 0.4942, 0.4841, 0.9571, 0.8028, 0.1227, 0.4124, 0.0661, 0.5776,
        0.8452, 0.4770, 0.0161, 0.8661, 0.1766, 0.1929, 0.2103, 0.8543, 0.5927,
        0.7728, 0.7813, 0.2794, 0.0914, 0.6574, 0.4325, 0.7467, 0.7509, 0.6309,
        0.6797, 0.6298, 0.8540, 0.7507, 0.4297, 0.1702, 0.3553, 0.2847, 0.6322,
        0.7822, 0.3285, 0.2423, 0.4749, 0.2355, 0.6806, 0.8486, 0.9917, 0.4051,
        0.7669, 0.2857, 0.7482, 0.7466, 0.0183, 0.4282, 0.2635, 0.0476, 0.8467,
        0.2954, 0.1735, 0.3974, 0.6684, 0.8744, 0.4771, 0.3136, 0.9146, 0.2972,
        0.8330])

In [25]:
# Initialize the weights of the neural network
weight_1 = torch.rand(784, 200)
weight_2 = torch.rand(200, 10)

# Multiply input_layer with weight_1
hidden_1 = torch.matmul(input_layer, weight_1)

# Multiply hidden_1 with weight_2
output_layer = torch.matmul(hidden_1,weight_2)
print(output_layer)

tensor([19978.9180, 21033.9336, 19594.5000, 20713.4941, 20507.1191, 21138.1641,
        21083.0996, 19682.3438, 19563.5957, 20250.4043])


In [26]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        
        # Instantiate all 2 linear layers  
        self.fc1 = nn.Linear(784, 200)
        self.fc2 = nn.Linear(200, 10)

    def forward(self, x):
      
        # Use the instantiated layers and return x
        x = self.fc1(x)
        x = self.fc2(x)
        return x

## Neural networks
Let us see the differences between neural networks which apply ReLU and those which do not apply ReLU. We have already initialized the input called input_layer, and three sets of weights, called weight_1, weight_2 and weight_3.<br>
We are going to convince ourselves that networks with multiple layers which do not contain non-linearity can be expressed as neural networks with one layer.

In [27]:
input_layer=torch.tensor([[ 0.0401, -0.9005,  0.0397, -0.0876]])
weight_1=torch.tensor([[-0.1094, -0.8285,  0.0416, -1.1222],
        [ 0.3327, -0.0461,  1.4473, -0.8070],
        [ 0.0681, -0.7058, -1.8017,  0.5857],
        [ 0.8764,  0.9618, -0.4505,  0.2888]])
weight_2=torch.tensor([[ 0.6856, -1.7650,  1.6375, -1.5759],
        [-0.1092, -0.1620,  0.1951, -0.1169],
        [-0.5120,  1.1997,  0.8483, -0.2476],
        [-0.3369,  0.5617, -0.6658,  0.2221]])
weight_3=torch.tensor([[ 0.8824,  0.1268,  1.1951,  1.3061],
        [-0.8753, -0.3277, -0.1454, -0.0167],
        [ 0.3582,  0.3254, -1.8509, -1.4205],
        [ 0.3786,  0.5999, -0.5665, -0.3975]])

In [28]:
# Calculate the first and second hidden layer
hidden_1 = torch.matmul(input_layer, weight_1)
hidden_2 = torch.matmul(hidden_1, weight_2)

# Calculate the output
print(torch.matmul(hidden_2, weight_3))

# Calculate weight_composed_1 and weight
weight_composed_1 = torch.matmul(weight_1, weight_2)
weight = torch.matmul(weight_composed_1, weight_3)

# Multiply input_layer with weight
print(torch.matmul(input_layer, weight))

tensor([[0.2653, 0.1311, 3.8219, 3.0032]])
tensor([[0.2653, 0.1311, 3.8219, 3.0032]])


## ReLU activation
In this exercise, we have the same settings as the previous exercise. But now we are going to build a neural network which has non-linearity. By doing so, we are going to convince ourselves that networks with multiple layers and non-linearity functions cannot be expressed as a neural network with one layer.



In [29]:
# Instantiate non-linearity
relu = nn.ReLU()

# Apply non-linearity on the hidden layers
hidden_1_activated = relu(torch.matmul(input_layer, weight_1))
hidden_2_activated = relu(torch.matmul(hidden_1_activated, weight_2))
print(torch.matmul(hidden_2_activated, weight_3))

# Apply non-linearity in the product of first two weights. 
weight_composed_1_activated = relu(torch.matmul(weight_1, weight_2))

# Multiply `weight_composed_1_activated` with `weight_3
weight = torch.matmul(weight_composed_1_activated, weight_3)

# Multiply input_layer with weight
print(torch.matmul(input_layer, weight))

tensor([[-0.2770, -0.0345, -0.1410, -0.0664]])
tensor([[-0.2117, -0.4782,  4.0438,  3.0417]])


In [30]:
# Instantiate ReLU activation function as relu
relu = nn.ReLU()

# Initialize weight_1 and weight_2 with random numbers
weight_1 = torch.rand(4, 6)
weight_2 = torch.rand(6, 2)

# Multiply input_layer with weight_1
hidden_1 = torch.matmul(input_layer, weight_1)

# Apply ReLU activation function over hidden_1 and multiply with weight_2
hidden_1_activated = relu(hidden_1)
print(torch.matmul(hidden_1_activated, weight_2))

tensor([[0., 0.]])


## Calculating loss function in PyTorch
You are going to code the previous exercise, and make sure that we computed the loss correctly. Predicted scores are -1.2 for class 0 (cat), 0.12 for class 1 (car) and 4.8 for class 2 (frog). The ground truth is class 2 (frog). Compute the loss function in PyTorch.

In [31]:
# Initialize the scores and ground truth
logits = torch.tensor([[-1.2, 0.12, 4.8]])
ground_truth = torch.tensor([2])

# Instantiate cross entropy loss
criterion = nn.CrossEntropyLoss()

# Compute and print the loss
loss = criterion(logits,ground_truth)
print(loss)

tensor(0.0117)


In [32]:
# Initialize logits and ground truth
logits = torch.rand(1,1000)
ground_truth = torch.tensor([111])

# Instantiate cross-entropy loss
criterion=nn.CrossEntropyLoss()

# Calculate and print the loss
loss = criterion(logits,ground_truth)
print(loss)

tensor(6.5726)


## Preparing a dataset in PyTorch

In [46]:
# pip install torchvision

import torchvision
import torch.utils.data
#import torchvision.transforms as transforms
from torchvision import transforms


### Transformation and Loading of CIFAR10 Dataset

<img src='https://miro.medium.com/max/1182/1*OSvbuPLy0PSM2nZ62SbtlQ.png' width="500" height="250">

In [47]:
#
transform=transforms.Compose(
    [transforms.ToTensor(),
    transforms.Normalize((0.4914, 0.48216, 0.44653),
                         (0.24703, 0.24349, 0.26159))])

In [48]:
trainset=torchvision.datasets.CIFAR10(root='./Data',train=True, download=True, transform=transform)

testset=torchvision.datasets.CIFAR10(root='./Data',train=False, download=True, transform=transform)

Files already downloaded and verified
Files already downloaded and verified


In [49]:
trainloader=torch.utils.data.DataLoader(trainset, batch_size=32,
                                        shuffle=True, num_workers=4)
testloader=torch.utils.data.DataLoader(testset, batch_size=32,
                                        shuffle=False, num_workers=4)                            

### Transformation and Loading of MNIST Dataset

<img src='https://www.researchgate.net/publication/306056875/figure/fig1/AS:393921575309346@1470929630835/Example-images-from-the-MNIST-dataset.png' width=400 height=400>

You are going to prepare dataloaders for MNIST training and testing set. As we explained in the lecture, MNIST has some differences to CIFAR-10, with the main difference being that MNIST images are grayscale (1 channel based) instead of RGB (3 channels).<br>
<li>Transform the data to torch tensors and normalize it to have mean is 0.1307 and std is 0.3081.</li>
<li>Prepare the trainset and the testset.</li>
<li>Prepare the dataloaders for training and testing so that only 32 pictures are processed at a time and the training data is shuffled each time.</li>

In [53]:
# Transform the data to torch tensors and normalize it 
transform_ = transforms.Compose([transforms.ToTensor(),
								transforms.Normalize((0.1307), ((0.3081)))])

# Prepare training set and testing set
train_set = torchvision.datasets.MNIST(root='./Data', train=True, 
									  download=True, transform=transform_)
test_set = torchvision.datasets.MNIST(root='./Data', train=False,
			   download=True, transform=transform_)

# Prepare training loader and testing loader
train_loader = torch.utils.data.DataLoader(train_set, batch_size=32,
                                          shuffle=True, num_workers=0)
test_loader = torch.utils.data.DataLoader(test_set, batch_size=32,
										 shuffle=False, num_workers=0) 

In [55]:

train_loader.dataset.train_data.shape

/Users/hadi/opt/anaconda3/envs/py/lib/python3.9/site-packages/torchvision/datasets/mnist.py:75: UserWarning: train_data has been renamed data
  warnings.warn("train_data has been renamed data")


torch.Size([60000, 28, 28])

In [56]:
test_loader.dataset.test_data.shape

/Users/hadi/opt/anaconda3/envs/py/lib/python3.9/site-packages/torchvision/datasets/mnist.py:80: UserWarning: test_data has been renamed data
  warnings.warn("test_data has been renamed data")


torch.Size([10000, 28, 28])

In [57]:
train_loader.batch_size

32

In [58]:
test_loader.batch_size

32

In [59]:
train_loader.sampler

In [43]:
# Compute the shape of the training set and testing set
trainset_shape = trainloader.dataset.train_data.shape
testset_shape = testloader.dataset.test_data.shape

# Print the computed shapes
print(trainset_shape, testset_shape)

# Compute the size of the minibatch for training set and testing set
trainset_batchsize = trainloader.batch_size
testset_batchsize = testloader.batch_size

# Print sizes of the minibatch
print(trainset_batchsize, testset_batchsize)

torch.Size([60000, 28, 28]) torch.Size([10000, 28, 28])
32 32


## Training neural networks

## CIFAR10

In [44]:
from torch.nn import functional as F
from torch import optim

In [45]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1=nn.Linear(32*32*3,500)
        self.fc2=nn.Linear(500,10)
    
    def forward(self, x):
        x= F.relu(self.fc1(x))
        return self.fc2(x)


In [50]:
net=Net()
criterion=nn.CrossEntropyLoss()
optimizer=optim.Adam(net.parameters(),lr=3e-4)

for epoch in range(10): #loop over the dataset multiple times
    for i, data in enumerate(trainloader,0):
        #get the inputs
        inputs, labels = data
        inputs=inputs.view(-1, 32 * 32 * 3)

        # Zero the parameter Gradients
        optimizer.zero_grad()

        #Forward + backward + optimize
        outputs=net(inputs)
        loss=criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        


In [51]:
correct, total = 0, 0
predictions= []
net.eval()
for i, data in enumerate(testloader, 0):
    inputs, labels = data
    inputs = inputs.view(-1, 32 * 32 * 3)
    outputs=net(inputs)
    _, predicted = torch.max(outputs.data, 1)
    predictions.append(outputs)
    total +=labels.size(0)
    correct +=(predicted==labels).sum().item()

print("the testing set accuracy of the network is : %d  %%" %(100 *correct/total))    

the testing set accuracy of the network is : 52  %


## MNIST

In [52]:
# Define the class Net
class Net(nn.Module):
    def __init__(self):    
    	# Define all the parameters of the net
        super(Net, self).__init__()
        self.fc1 = nn.Linear(28 * 28 * 1, 200)
        self.fc2 = nn.Linear(200, 10)

    def forward(self, x):   
    	# Do the forward pass
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return x

In [60]:
# Instantiate the Adam optimizer and Cross-Entropy loss function
model = Net()   
optimizer = optim.Adam(model.parameters(), lr=3e-4)
criterion = nn.CrossEntropyLoss()
  
for batch_idx, data_target in enumerate(train_loader):
    data = data_target[0]
    target = data_target[1]
    data = data.view(-1, 28 * 28)
    optimizer.zero_grad()

    # Complete a forward pass
    output = model(data)

    # Compute the loss, gradients and change the weights
    loss = criterion(output,target)
    loss.backward()
    optimizer.step()

In [61]:
# Set the model in eval mode
model.eval( )

for i, data in enumerate(test_loader, 0):
    inputs, labels = data
    
    # Put each image into a vector
    inputs = inputs.view(-1, 28 * 28 * 1)
    
    # Do the forward pass and get the predictions
    outputs = model(inputs)
    _, outputs = torch.max(outputs.data, 1)
    total += labels.size(0)
    correct += (outputs == labels).sum().item()
print('The testing set accuracy of the network is: %d %%' % (100 * correct / total))

The testing set accuracy of the network is: 74 %


## Convolution operator

In [62]:
# OOP (torch.nn)
# in_channels (int) number of chennels in inut
# out_chennels (int) number of channels produced by the convolution
# Kernel_size (int or tuple) size of the konvolving kernel
# stride (int or tuple, optional) Stride of the convolution. Default:1
# padding (int or tuple, optional) Zero padding
image = torch.rand(16, 3, 32, 32)
conv_filter = torch.nn.Conv2d(in_channels= 3, out_channels= 1,
                                kernel_size= 5, stride= 1, padding= 0)
output_feature = conv_filter(image)
print(output_feature.shape)



# functional (torch.nn.functional)
# input - input tensor of shape (minibatch x in_channels x iH x iW)
# weight - filters of shape (out_channels x in_channels x kH x kW)
# stride - the stride of the convolving kernel. can be a single number or tuple (sH,sW). Default: 1
# padding - implicit zero padding on both side of the input. can be s single number ot tuple (padH, padW). Default : 0

image = torch.rand(16, 3, 32, 32)
filter = torch.rand(1, 3, 5, 5)
out_feat_F = F.conv2d(image, filter,
                    stride= 1, padding = 0)
print(out_feat_F.shape)

torch.Size([16, 1, 28, 28])
torch.Size([16, 1, 28, 28])


In [63]:
# Convolution operator - OOP way

# Create 10 images with shape (1, 28, 28).
# Build 6 convolutional filters of size (3, 3) with stride set to 1 and padding set to 1.
# Apply the filters in the image and print the shape of the feature map.

# Create 10 random images of shape (1, 28, 28)
images = torch.rand(10, 1, 28, 28)

# Build 6 conv. filters
conv_filters = torch.nn.Conv2d(in_channels=1, out_channels=6, kernel_size=3, stride=1, padding=1)

# Convolve the image with the filters 
output_feature = conv_filters(images)
print(output_feature.shape)

torch.Size([10, 6, 28, 28])


In [64]:
# Convolution operator - Functional way
# Create 10 random images with shape (1, 28, 28).
# Create 6 random filters with shape (1, 3, 3).
# Convolve the images with the filters.

# Create 10 random images
image = torch.rand(10, 1, 28, 28)

# Create 6 filters
filters = torch.rand(6, 1, 3, 3)

# Convolve the image with the filters
output_feature = F.conv2d(image, filters, stride=1, padding=1)
print(output_feature.shape)


torch.Size([10, 6, 28, 28])


## Pooling operators

In [67]:
# OOP
im = torch.Tensor([[[3, 1, 3, 5], [6, 0, 7, 9], [3, 2, 1, 4], [0, 2, 4, 3]]])
# max pooling
max_pooling = torch.nn.MaxPool2d(2)
output_feature = max_pooling(im)
print(output_feature)
# average pooling
avg_pooling = torch.nn.AvgPool2d(2)
output_feature = avg_pooling(im)
print(output_feature)


# functional
# Max
output_feature_F = F.max_pool2d(im,2)
print(output_feature_F)
# average
output_feature_F = F.avg_pool2d(im,2)
print(output_feature_F)


tensor([[[6., 9.],
         [3., 4.]]])
tensor([[[2.5000, 6.0000],
         [1.7500, 3.0000]]])
tensor([[[6., 9.],
         [3., 4.]]])
tensor([[[2.5000, 6.0000],
         [1.7500, 3.0000]]])


In [70]:
tensor=torch.tensor([[[[ 8.,  1.,  2.,  5.,  3.,  1.],
          [ 6.,  0.,  0., -5.,  7.,  9.],
          [ 1.,  9., -1., -2.,  2.,  6.],
          [ 0.,  4.,  2., -3.,  4.,  3.],
          [ 2., -1.,  4., -1., -2.,  3.],
          [ 2., -4.,  5.,  9., -7.,  8.]]]])


# Build a pooling operator with size `2`.
max_pooling = torch.nn.MaxPool2d(2)

# Apply the pooling operator
output_feature = max_pooling(tensor)

# Use pooling operator in the image
output_feature_F = F.max_pool2d(tensor,2)

# print the results of both cases
print(output_feature)
print(output_feature_F)

tensor([[[[8., 5., 9.],
          [9., 2., 6.],
          [2., 9., 8.]]]])
tensor([[[[8., 5., 9.],
          [9., 2., 6.],
          [2., 9., 8.]]]])


In [71]:
# Build a pooling operator with size `2`.
avg_pooling = torch.nn.AvgPool2d(2)

# Apply the pooling operator
output_feature = avg_pooling(tensor)

# Use pooling operator in the image
output_feature_F = F.avg_pool2d(tensor,2)

# print the results of both cases
print(output_feature)
print(output_feature_F)

tensor([[[[ 3.7500,  0.5000,  5.0000],
          [ 3.5000, -1.0000,  3.7500],
          [-0.2500,  4.2500,  0.5000]]]])
tensor([[[[ 3.7500,  0.5000,  5.0000],
          [ 3.5000, -1.0000,  3.7500],
          [-0.2500,  4.2500,  0.5000]]]])


## Convolutional Neural Networks