# DeepLearning with Pytorch
DataCamp Course

In [2]:
# pip install torch
import numpy as np
import torch

## Creating tensors in PyTorch
Random tensors are very important in neural networks. Parameters of the neural networks typically are initialized with random weights (random tensors).



In [18]:
list1=[2,3,5]
list2=[1,2,9]
torch.tensor([list1,list2])

tensor([[2, 3, 5],
        [1, 2, 9]])

In [19]:
np.array([list1,list2])

array([[2, 3, 5],
       [1, 2, 9]])

In [31]:
#multiplcation with pytorch
mat1=torch.rand(4,4)
mat2=torch.rand(4,4)
multmat=torch.matmul(mat1,mat2)
multmat

tensor([[2.0166, 1.7149, 2.0680, 1.8962],
        [2.0816, 1.6449, 2.0028, 1.6407],
        [1.3223, 1.2938, 1.4979, 1.3945],
        [1.0873, 0.7426, 0.9934, 0.9451]])

In [32]:
#element multiplication
mat1 * mat2

tensor([[0.2267, 0.4928, 0.4918, 0.6619],
        [0.0953, 0.0612, 0.2552, 0.5078],
        [0.9405, 0.1405, 0.2718, 0.3306],
        [0.0960, 0.7073, 0.4608, 0.1454]])

In [33]:
#multiplication with Numpy
mat1=np.random.rand(4,4)
mat2=np.random.rand(4,4)
multmat=np.dot(mat1,mat2)
multmat

array([[1.12754878, 0.85733287, 1.23747869, 1.0127282 ],
       [1.07296251, 1.16571859, 1.19272448, 1.14941114],
       [1.39294344, 0.83636715, 1.39027568, 1.04029302],
       [0.9928961 , 0.31433012, 0.88691205, 0.87661795]])

In [34]:
#element multiplication
np.multiply(mat1,mat2)

array([[0.27535674, 0.92081175, 0.38278094, 0.51026539],
       [0.15748971, 0.14487037, 0.05340088, 0.03931516],
       [0.21510058, 0.01592962, 0.13466538, 0.68922102],
       [0.07689088, 0.03990748, 0.68427285, 0.15047132]])

In [35]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [37]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [38]:
torch.eye(2,2)

tensor([[1., 0.],
        [0., 1.]])

In [40]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [42]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [43]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [45]:
torch.from_numpy(np.identity(2))

tensor([[1., 0.],
        [0., 1.]], dtype=torch.float64)

In [47]:
torch.eye(2,2).numpy()

array([[1., 0.],
       [0., 1.]], dtype=float32)

In [16]:
# Create random tensor of size 3 by 3
your_first_tensor = torch.rand(3, 3)

# Calculate the shape of the tensor
tensor_size = your_first_tensor.shape

# Print the values of the tensor and its shape
print(your_first_tensor)
print(tensor_size)

tensor([[0.4598, 0.6097, 0.8728],
        [0.6495, 0.0638, 0.8282],
        [0.6361, 0.8120, 0.2330]])
torch.Size([3, 3])


In [6]:
#same things in Numpy
# Create random tensor of size 3 by 3
your_first_tensor = np.random.rand(3, 3)

# Calculate the shape of the tensor
tensor_size = your_first_tensor.shape

# Print the values of the tensor and its shape
print(your_first_tensor)
print(tensor_size)

[[0.74010236 0.80915197 0.84563443]
 [0.9775519  0.93318597 0.34364613]
 [0.58134982 0.33891279 0.75384948]]
(3, 3)


In [49]:
# Create a matrix of ones with shape 3 by 3
tensor_of_ones = torch.ones(3, 3)

# Create an identity matrix with shape 3 by 3
identity_tensor = torch.eye(3)

# Do a matrix multiplication of tensor_of_ones with identity_tensor
matrices_multiplied = torch.matmul(tensor_of_ones, identity_tensor)
print(matrices_multiplied)

# Do an element-wise multiplication of tensor_of_ones with identity_tensor
element_multiplication = tensor_of_ones*identity_tensor
print(element_multiplication)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


## Forward pass
Let's have something resembling more a neural network. The computational graph has been given below. You are going to initialize 3 large random tensors, and then do the operations as given in the computational graph. The final operation is the mean of the tensor, given by torch.mean(your_tensor).

In [50]:
# Initialize tensors x, y and z
x = torch.rand(1000, 1000)
y = torch.rand(1000, 1000)
z = torch.rand(1000, 1000)

# Multiply x with y
q = torch.matmul(x,y)

# Multiply elementwise z with q
f = torch.matmul(z,q)

mean_f = torch.mean(f)
print(mean_f)

tensor(124903.4922)


## Backpropagation using PyTorch
Here, you are going to use automatic differentiation of PyTorch in order to compute the derivatives of x, y and z from the previous exercise.

In [54]:
# Initialize x, y and z to values 4, -3 and 5
x = torch.tensor([4.], requires_grad=True)
y = torch.tensor([-3.], requires_grad=True)
z = torch.tensor([5.],requires_grad=True)

# Set q to sum of x and y, set f to product of q with z
q = x+y
f = z*q

# Compute the derivatives
f.backward()

# Print the gradients
print("Gradient of x is: " + str(x.grad))
print("Gradient of y is: " + str(y.grad))
print("Gradient of z is: " + str(z.grad))

Gradient of x is: tensor([5.])
Gradient of y is: tensor([5.])
Gradient of z is: tensor([1.])
